basic readme
FACN7/the-experts pull request #29
Opened 2019-11-25 09:58 UTC by ebraheemabbas

adding some instruction ,User journey & goals
closes #8

2019-11-25 09:59 UTC, HosenAgbaria submitted a review, later dismissed

2019-11-25 10:00 UTC, omriza5 submitted a review, later dismissed

2019-11-25 10:06 UTC, jamiecoe requested changes

2019-11-25 10:06 UTC, jamiecoe commented on README.md
> +Well, it's and app for connecting contractors with users, you can enter to the app and search for a contractor
Here you can put the User Journey we created - 'Allow a user to find a suitable contractor'. Also the User Stories we created:

- As a User, I want to search for a contractor (based on job title) and see a list of results
- As a User, I want to come to homepage and understand what the website is for

2019-11-25 10:06 UTC, jamiecoe commented on README.md
> +Runs the app in the development mode.<br />
Won't this start the Express server on Port 9000? What about starting the React server? You could make one command in top level `package.json` to start them both at same time using the [`concurrently`](https://www.npmjs.com/package/concurrently) npm package.

2019-11-27 14:13 UTC, omriza5 submitted a review, later dismissed

2019-11-27 14:14 UTC, jamiecoe submitted a review, later dismissed

2019-11-27 14:39 UTC, jamiecoe approved these changes

2019-11-27 15:03 UTC, HosenAgbaria approved these changes

2019-11-27 15:03 UTC, omriza5 approved these changes

2019-11-27 15:03 UTC, merged