updated the home page...
FACN7/the-experts pull request #32
Opened 2019-11-26 03:12 UTC by later009

2019-11-26 07:32 UTC, jamiecoe requested changes
Before merging this PR, we should merge Omri's Render Search Data PR #31 - I've requested some changes so these just need to be fixed first. 

The additional stuff here looks good apart from the formatting!! Please please start using a formatting tool like Prettier, it makes the code so much easier to read.

Fix the formatting and then this PR will be ready to merge once #31 is merged.

2019-11-26 13:47 UTC, jamiecoe requested changes

2019-11-26 13:47 UTC, jamiecoe commented on the-experts-fe/src/App.js
>        .then(res => res.text())
Remember to use `res.json()` instead of `res.text()` here as the content-type of the response is JSON.

2019-11-26 13:47 UTC, jamiecoe commented on the-experts-fe/src/App.css
> +   margin-top: 1100px;
Still have dodgy formatting here! Use Prettier 💅

2019-11-26 13:47 UTC, jamiecoe commented on the-experts-fe/src/App.js
>  <WhyUs imageSrc="https://icon-library.net/images/filtering-icon/filtering-icon-5.jpg" description1="Get filtered data" description2="we filter the constructors data to  make sure that you will get th
Dodgy formatting! Use Prettier 💅

2019-11-26 14:18 UTC, omriza5 approved these changes

2019-11-26 14:23 UTC, ebraheemabbas approved these changes

2019-11-27 07:55 UTC, jamiecoe approved these changes

2019-11-27 07:55 UTC, merged