Host
FACN7/the-experts pull request #34
Opened 2019-11-26 14:10 UTC by ebraheemabbas

make some change in package.json
build react app
host to heroku
closes #7

2019-11-26 14:20 UTC, omriza5 submitted a review, later dismissed

2019-11-26 14:22 UTC, HosenAgbaria submitted a review, later dismissed

2019-11-26 15:47 UTC, jamiecoe requested changes
Great work on hosting to Heroku 🎉 

It seems you've now accidentally got an extra `the-experts-fe` inside your `the-experts-BE` folder. Please can you remove this from this PR.

2019-11-26 15:47 UTC, jamiecoe commented on the-experts-BE/app.js
> +console.log('we2e7', process.env.NODE_ENV)
Remove `console.log` 😭😭😭

2019-11-26 15:47 UTC, jamiecoe commented on the-experts-BE/app.js
> +  console.log('we2e72', process.env.NODE_ENV)
Remove `console.log` 😭😭😭

2019-11-26 15:47 UTC, jamiecoe commented on the-experts-BE/the-experts-fe/src/App.js
> +    // console.log(process.env.REACT_APP_testAPI2)
Please remove commented out code!

2019-11-26 15:47 UTC, jamiecoe commented on the-experts-fe/src/App.js
>        .then(res => res.text())
Remember you should use `res.json()` instead of `res.text()` here, because the content-type of the returned data is JSON.

2019-11-26 15:47 UTC, jamiecoe commented on the-experts-BE/README.md
> +- [ ] host to heroku
You've now done `fetch contractor's data from our DB` / `display data` / `host to heroku`. These can be ticked off 👍

2019-11-27 08:48 UTC, jamiecoe approved these changes

2019-11-27 08:49 UTC, omriza5 approved these changes

2019-11-27 08:53 UTC, HosenAgbaria approved these changes

2019-11-27 08:53 UTC, merged