add new express route for adding contractors
FACN7/the-experts pull request #39
Opened 2019-11-27 14:43 UTC by ebraheemabbas

add new route
add the route to the app.js
Relates #16

2019-11-27 14:44 UTC, omriza5 submitted a review, later dismissed

2019-11-27 14:58 UTC, jamiecoe requested changes

2019-11-27 14:58 UTC, jamiecoe commented on the-experts-BE/routes/contractor-post.js
> +      res.send(response.rows);
You should use `res.json()` to make it clear you are sending the data to the client as JSON.

2019-11-27 15:00 UTC, HosenAgbaria submitted a review, later dismissed

2019-11-28 08:12 UTC, omriza5 approved these changes

2019-11-28 08:12 UTC, jamiecoe approved these changes

2019-11-28 08:34 UTC, HosenAgbaria approved these changes

2019-11-28 09:26 UTC, merged